services:
  app:
    build: .
    container_name: app
    environment:
       MONGODB_CONNECTION_STRING: mongodb://mongo:27017/dailydlebot
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
     - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
